ALTER TABLE PROM_ENROLLMENT_ENTITY DROP CONSTRAINT FKc3n5e8uqv5ox68igiuotqt0di;
ALTER TABLE PROM_ENROLLMENT_ENTITY DROP CONSTRAINT FK9ttgh1ki3pcuh649smbhq65ko;
ALTER TABLE PROM_ENROLLMENT_ENTITY DROP CONSTRAINT FKo517lukxc0403in5onhthqsf5;
ALTER TABLE STUDENT_ROLE DROP CONSTRAINT FK3xafvie9u9yekdoyjk54ab9vo;
ALTER TABLE STUDENT_ROLE DROP CONSTRAINT FKre4g4cqgpgmot7x83cnkraq63;
ALTER TABLE TRIP_ENTITY DROP CONSTRAINT FK51qxcbjtcbevwa9yo0t2eg0gw;

TRUNCATE TABLE PROM_ENROLLMENT_ENTITY;
TRUNCATE TABLE PROM_PERSON_ENTITY;
TRUNCATE TABLE TRIP_ENTITY;
TRUNCATE TABLE STUDENT_ENTITY;
TRUNCATE TABLE STUDENT_ROLE;
TRUNCATE TABLE ROLE_ENTITY;

ALTER TABLE PROM_ENROLLMENT_ENTITY ADD CONSTRAINT FKc3n5e8uqv5ox68igiuotqt0di FOREIGN KEY (MAIN_PERSON_PROM_PERSON_ID) REFERENCES PROM_PERSON_ENTITY;
ALTER TABLE PROM_ENROLLMENT_ENTITY ADD CONSTRAINT FK9ttgh1ki3pcuh649smbhq65ko FOREIGN KEY (PARTNER_PROM_PERSON_ID) REFERENCES PROM_PERSON_ENTITY;
ALTER TABLE PROM_ENROLLMENT_ENTITY ADD CONSTRAINT FKo517lukxc0403in5onhthqsf5 FOREIGN KEY (USER_ID) REFERENCES STUDENT_ENTITY;
ALTER TABLE STUDENT_ROLE ADD CONSTRAINT FK3xafvie9u9yekdoyjk54ab9vo FOREIGN KEY (ROLE_ID) REFERENCES ROLE_ENTITY;
ALTER TABLE STUDENT_ROLE ADD CONSTRAINT FKre4g4cqgpgmot7x83cnkraq63 FOREIGN KEY (USER_ID) REFERENCES STUDENT_ENTITY;
ALTER TABLE TRIP_ENTITY ADD CONSTRAINT FK51qxcbjtcbevwa9yo0t2eg0gw FOREIGN KEY (USER_ID) REFERENCES STUDENT_ENTITY;
